---
title: "eda"
author: "Manye Dong"
date: "2023-10-05"
output: github_document
---
```{r}
library(tidyverse)
library(dplyr)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    # floor_date is to round down the date in one month
    month = lubridate::floor_date(date, unit = "month")) |>
  select(name, id, everything())
```
```{r}
weather_df
```

## Initial Numeric work
```{r}
weather_df |> 
  ggplot(aes(x = prcp)) + 
  geom_histogram()
```

Here are the big outliers: any formal analyses involving precipitation as a predictor or outcome might be influenced by this fact
```{r}
weather_df |> filter(prcp > 1000)
```

```{r}
weather_df |> 
  filter(tmax >= 20, tmax <= 30) |> 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  geom_point(alpha = .75)
```

